#!/usr/bin/env python3
"""Generate the VAPID keypair that web push needs.

Web push identifies the sender with a P-256 keypair. The public key is baked
into the web page; the private key signs each push and must stay secret.

Run once:

    python3 make_vapid.py

Written with openssl rather than a Python crypto library so it works on a stock
macOS Python with nothing installed.
"""

import base64
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PUBLIC_PATH = os.path.join(ROOT, "web", "vapid-public-key.js")
PRIVATE_PATH = os.path.join(ROOT, "vapid-private-key.txt")


def b64url(raw):
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def _hex_block(text, label):
    """Pull one of openssl's indented hex blocks out of `ec -text` output."""
    match = re.search(
        r"^%s:\s*\n((?:\s+[0-9a-f:]+\s*\n)+)" % label, text, re.M)
    if not match:
        raise SystemExit("Could not read the %s key from openssl output." % label)
    return bytes.fromhex(re.sub(r"[^0-9a-f]", "", match.group(1)))


def generate():
    pem = subprocess.run(
        ["openssl", "ecparam", "-genkey", "-name", "prime256v1", "-noout"],
        capture_output=True, check=True).stdout
    text = subprocess.run(
        ["openssl", "ec", "-text", "-noout"],
        input=pem, capture_output=True, check=True).stdout.decode()

    private = _hex_block(text, "priv")
    public = _hex_block(text, "pub")

    # openssl may pad the private scalar to 33 bytes with a leading zero, or
    # emit fewer than 32 if the value is small. Web push wants exactly 32.
    private = private[-32:].rjust(32, b"\x00")

    if len(public) != 65 or public[0] != 0x04:
        raise SystemExit("Expected a 65-byte uncompressed public point.")

    return b64url(private), b64url(public), pem


def main():
    if os.path.exists(PRIVATE_PATH):
        print("A key already exists at %s" % PRIVATE_PATH)
        print("Delete it first if you really want a new one - replacing the key")
        print("stops every phone already subscribed from receiving pushes.")
        return 1

    private_b64, public_b64, pem = generate()

    with open(PUBLIC_PATH, "w") as handle:
        handle.write("// Generated by make_vapid.py - safe to publish.\n")
        handle.write('window.VAPID_PUBLIC_KEY = "%s";\n' % public_b64)

    with open(PRIVATE_PATH, "w") as handle:
        handle.write(private_b64 + "\n")
    os.chmod(PRIVATE_PATH, 0o600)

    with open(os.path.join(ROOT, "vapid-private-key.pem"), "wb") as handle:
        handle.write(pem)
    os.chmod(os.path.join(ROOT, "vapid-private-key.pem"), 0o600)

    print("Public key  (published in the web app):")
    print("  %s\n" % public_b64)
    print("Private key (goes in a GitHub secret, never commit it):")
    print("  %s\n" % private_b64)
    print("Saved to %s" % PRIVATE_PATH)
    return 0


if __name__ == "__main__":
    sys.exit(main())
